### ISSUE TITLE
SendImage is broken since v0.0.3 (Spout 2.006)

### ISSUE THREAD

**Issue by cansik** [jlai/Python-SpoutGL#15]
With the update from Spout `2.006` to `2.007h` the `sendImage` command is broken, only texture sharing is possible. The sender is created correctly, but the following method does not go in either of the [two if statements](https://github.com/leadedge/Spout2/blob/2.007h/SPOUTSDK/SpoutGL/Spout.cpp#L535-L542). At the end just returns false, because texture sharing and cpu sharing is not available.

```cpp
if (m_bTextureShare) {
	// Texture share compatible
	return WriteGLDXpixels(pixels, width, height, glformat, bInvert, HostFBO);
}
else if (m_bCPUshare) {
	// Auto share enabled for DirectX CPU backup
	return WriteDX11pixels(pixels, width, height, glformat, bInvert);
}
```

I am currently not sure how fix this, playing around with auto-share and cpu-share flags did not help:

```python
sender.setCPUshare(True)
sender.setAutoShare(False)
```

Do you have an idea what could be the problem here?

If I just force the CPUShare code (by copying it out of the if statement), the sharing works as expected.

**Comment by jlai** [comment]
No idea off the top of my head. Might have to look into how `m_bTextureShare` and `m_bCPUshare` get set and if they're being unset somewhere.
