### ISSUE TITLE
Get Senders

### ISSUE THREAD

**Issue by Sash0check** [jlai/Python-SpoutGL#50]
Hello! I'm trying to get availible senders. But I didn't found solution fot it. Thank you in advance)

**Comment by jlai** [comment]
At the moment that API isn't available in this Python wrapper, but it wouldn't be difficult to add

**Comment by jo-chemla** [comment]
Hi there, would love to see if this `Spout Senders Discovery` feature could be implemented. Any pointer would be appreciated, thanks!

**Comment by jlai** [comment]
I added `getSenderList()` and a couple other APIs related to listing senders. Let me know if there's anything else needed?

https://github.com/jlai/Python-SpoutGL/releases/tag/v0.1.0

**Comment by jo-chemla** [comment]
Wow that was fast thank you so much! This will be useful to the blender [texture streaming addon](https://github.com/maybites/TextureSharing/), for spout texture sharing. I'll tell the maintainer about these added API.
