### ISSUE TITLE
How to cleanly exit spout?

### ISSUE THREAD

**Issue by kyeshmz** [jlai/Python-SpoutGL#61]
Hi I have been using the package to great success, but have been increasingly seeing errors around memory when exiting.
I think it is due to name issues with the sender name as well as spout not exiting cleanly. 
How can I exit as clean as possible to remove all the memory, etc. before the program exits?

**Comment by rwebber** [comment]
Following. 
I suspect disposing of Spout is at the heart of some issues I have faced as well.

**Comment by jlai** [comment]
Are you using releaseSender/releaseReceiver?

**Comment by kyeshmz** [comment]
Turns out I did need to release both sender and receiver, as well as fix an async issue. Thanks for the tips!
